version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    ignore:
    - dependency-name: "k8s.io/*"
      update-types: ["version-update:semver-major", "version-update:semver-minor"] # ignore all except for patch updates
    - dependency-name: "github.com/vmware/go-ipfix"
    - dependency-name: "github.com/TomCodeLV/OVSDB-golang-lib"
    - dependency-name: "github.com/contiv/libOpenflow"
    - dependency-name: "github.com/ofnet/libOpenflow"
    - dependency-name: "github.com/vmware-tanzu/octant"
      update-types: ["version-update:semver-major", "version-update:semver-minor"] # ignore all except for patch updates
    - dependency-name: "github.com/Microsoft/hcsshim" # we use a replace directive for this dependency
  - package-ecosystem: "github-actions"
    # Workflow files stored in the default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
