# Site settings
title: Antrea
email:
author: Antrea Authors
description: Validate your Kubernetes configuration
url: https://github.com/vmware-tanzu/antrea
logo: antrea-logo.svg
twitter:
  username: projectantrea
  card: summary
vm_logo: vm-logo.png
gh_repo: https://github.com/vmware-tanzu/antrea
markdown: redcarpet
hero:
  background-color: med-blue
footer:
  title: Getting Started
  content: To help you get started, see the documentation.
  cta_title:
  cta_url: /docs
  cta_text: Documentation
  vm-link: http://vmware.github.io/
footer_social_links:
  Twitter:
    fa_icon: fab fa-twitter
    url: https://twitter.com/projectantrea
  Slack:
    fa_icon: fab fa-slack
    url: https://kubernetes.slack.com/archives/CR2J23M0X
  #RSS:
  #  fa_icon: fa fa-rss
  #  url: feed.xml
  GitHub:
    fa_icon: fab fa-github
    url: https://github.com/vmware-tanzu/antrea
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "posts"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: docs/main
    values:
      version: main
      gh: https://github.com/vmware-tanzu/antrea/tree/master
      layout: "docs"
  - scope:
      path: docs/v0.9.2
    values:
      version: v0.9.2
      gh: https://github.com/vmware-tanzu/antrea/tree/v0.9.2
      layout: "docs"
  - scope:
      path: docs/v0.9.3
    values:
      version: v0.9.3
      gh: https://github.com/vmware-tanzu/antrea/tree/v0.9.3
      layout: "docs"
  - scope:
      path: docs/v0.10.0
    values:
      version: v0.10.0
      gh: https://github.com/vmware-tanzu/antrea/tree/v0.10.0
      layout: "docs"
  - scope:
      path: docs/v0.10.1
    values:
      version: v0.10.1
      gh: https://github.com/vmware-tanzu/antrea/tree/v0.10.1
      layout: "docs"
  - scope:
      path: docs/v0.10.2
    values:
      version: v0.10.2
      gh: https://github.com/vmware-tanzu/antrea/tree/v0.10.2
      layout: "docs"
  - scope:
      path: docs/v0.11.0
    values:
      version: v0.11.0
      gh: https://github.com/vmware-tanzu/antrea/tree/v0.11.0
      layout: "docs"
  - scope:
      path: docs/v0.11.1
    values:
      version: v0.11.1
      gh: https://github.com/vmware-tanzu/antrea/tree/v0.11.1
      layout: "docs"
  - scope:
      path: docs/v0.11.2
    values:
      version: v0.11.2
      gh: https://github.com/vmware-tanzu/antrea/tree/v0.11.2
      layout: "docs"
  - scope:
      path: docs/v0.11.3
    values:
      version: v0.11.3
      gh: https://github.com/vmware-tanzu/antrea/tree/v0.11.3
      layout: "docs"
  - scope:
      path: docs/v0.12.0
    values:
      version: v0.12.0
      gh: https://github.com/vmware-tanzu/antrea/tree/v0.12.0
      layout: "docs"
  - scope:
      path: docs/v0.12.1
    values:
      version: v0.12.1
      gh: https://github.com/vmware-tanzu/antrea/tree/v0.12.1
      layout: "docs"
  - scope:
      path: docs/v0.12.2
    values:
      version: v0.12.2
      gh: https://github.com/vmware-tanzu/antrea/tree/v0.12.2
      layout: "docs"
  - scope:
      path: docs/v0.13.0
    values:
      version: v0.13.0
      gh: https://github.com/vmware-tanzu/antrea/tree/v0.13.0
      layout: "docs"
  - scope:
      path: docs/v0.13.1
    values:
      version: v0.13.1
      gh: https://github.com/vmware-tanzu/antrea/tree/v0.13.1
      layout: "docs"
  - scope:
      path: docs/v1.0.0
    values:
      version: v1.0.0
      gh: https://github.com/vmware-tanzu/antrea/tree/v1.0.0
      layout: "docs"
  - scope:
      path: docs/v1.0.1
    values:
      version: v1.0.1
      gh: https://github.com/vmware-tanzu/antrea/tree/v1.0.1
      layout: "docs"
page_gen:
  - data: shortlinks
    template: redirect
    name: key
    dir: docs
collections:
  - contributors
  - features
  - presentations
versioning: true
latest: v1.0.1
versions:
  - main
  - v1.0.1
  - v1.0.0
  - v0.13.1
  - v0.13.0
  - v0.12.2
  - v0.12.1
  - v0.12.0
  - v0.11.3
  - v0.11.2
  - v0.11.1
  - v0.11.0
  - v0.10.2
  - v0.10.1
  - v0.10.0
  - v0.9.3
  - v0.9.2
# Build settings
permalink: :title/
sass:
  sass_dir: css
  style: :compressed
# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-relative-links # Used to auto generate md links to html links
  - jekyll-optional-front-matter # Parse Markdown files that do not have front-matter callouts
  - jekyll-readme-index # use README.md as index.html
  - jekyll-titles-from-headings # pull the page title from the first Markdown heading when none is specified.
  - jekyll-paginate # pagination object for collections (e.g. posts)
  - jekyll-redirect-from
  - jekyll-seo-tag
# Include these subdirectories
include:
  - CONTRIBUTING.md
  - README.md
  - CODE_OF_CONDUCT.md
# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - README-JEKYLL.md
  - LICENSE
  - CNAME
  - Runbook.docx
  - '*.sh'
redcarpet:
  extensions: ["no_intra_emphasis", "tables", "autolink", "strikethrough", "with_toc_data"]
