namespace: kube-system

namePrefix: antrea-mc-

commonLabels:
  app: antrea

bases:
  - ../../crd
  - ../../default

patchesJson6902:
- target:
    group: rbac.authorization.k8s.io
    version: v1
    kind: ClusterRole
    name: controller-role
  path: additional_role_patch.yaml

configurations:
  - kustomizeconfig.yaml

patchesStrategicMerge:
  - manager_command_patch.yaml
  - webhook_patch.yaml
