# permissions for end users to view gateways.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gatewaynode-viewer-role
rules:
- apiGroups:
  - multicluster.crd.antrea.io
  resources:
  - gateways
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - multicluster.crd.antrea.io
  resources:
  - gateways/status
  verbs:
  - get
