name: Go Benchmark Test

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      branch:
        description: 'Git branch to run benchmarks on'
        required: false
        default: main

jobs:
  go-benchmark-checks:
    name: GoBenchmark
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event_name == 'workflow_dispatch' && inputs.branch || 'main' }}
          fetch-depth: 0
          show-progress: false

      - name: Set up Go using version from .go-version
        uses: actions/setup-go@v6
        with:
          go-version-file: '.go-version'

      - name: Install benchci
        run: curl -sfL https://raw.githubusercontent.com/antrea-io/benchci/main/install.sh | sudo sh -s -- -b /usr/local/bin

      - name: Run benchmark
        run: benchci -config test/performance/benchmark.yml
