name: Cancel Workflows
on:
  workflow_run:
    workflows: ["Go", "Golicense", "Kind", "Build and push latest image if needed", "Antrea upgrade"]
    types:
      - requested
jobs:
  cancel:
    name: Cancel workflows
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.event == 'pull_request' }}
    steps:
    - uses: styfle/cancel-workflow-action@0.9.0
      with:
        workflow_id: ${{ github.event.workflow.id }}
