# Anyone with write permissions to the antrea-io/antrea Github repository can
# trigger this workflow manually, but please check with a maintainer first. The
# workflow will build and push the antrea/base-windows image.
name: Manually update antrea/base-windows Docker image

on:
  workflow_dispatch:
    inputs:
      antrea-repository:
        description: 'The Antrea repository to check-out'
        required: true
        type: string
      antrea-ref:
        description: 'The Git ref to use when checking-out the Antrea repository'
        required: true
        type: string
      push:
        description: 'Whether to push built base images to the Docker registry'
        required: false
        default: true
        type: boolean

jobs:
  build:
    runs-on: windows-2019
    steps:
    - name: Check-out code
      uses: actions/checkout@v4
      with:
        repository: ${{ github.event.inputs.antrea-repository }}
        ref: ${{ github.event.inputs.antrea-ref }}
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push Docker images
      if: ${{ github.event.inputs.push }}
      run: |
        ./hack/build-antrea-windows-all.sh --pull --push-base-images
      shell: bash
    - name: Build Docker images without pushing
      if: ${{ !github.event.inputs.push }}
      run: |
        ./hack/build-antrea-windows-all.sh --pull
      shell: bash
