name: Golicense
on:
  pull_request:
    branches:
    - main
    - release-*
  push:
    branches:
    - main
    - release-*
  release:
    types:
      - created

jobs:
  check-changes:
    name: Check whether tests need to be run based on diff
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: vmware-tanzu/antrea/ci/gh-actions/has-changes@main
      id: check_diff
      with:
        args: docs/* ci/jenkins/* *.md
    outputs:
      has_changes: ${{ steps.check_diff.outputs.has_changes }}

  golicense:
    needs: check-changes
    if: ${{ needs.check-changes.outputs.has_changes == 'yes' || github.event_name != 'pull_request' }}
    runs-on: [ubuntu-latest]
    steps:
    - name: Set up Go 1.15
      uses: actions/setup-go@v1
      with:
        go-version: 1.15
    - uses: actions/checkout@v2
    - name: Cache licensing information for dependencies
      uses: actions/cache@v2
      id: cache
      env:
        cache-name: cache-lichen-deps-licensing-info
      with:
        path: license-reports
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/go.sum') }}
    - run: mkdir antrea-bins
    - name: Build assets
      run: |
        export VERSION="$(head VERSION)"
        ./hack/release/prepare-assets.sh ./antrea-bins
    - name: Build Linux binaries
      run: BINDIR=./antrea-bins make bin
    - name: Run lichen
      if: steps.cache.outputs.cache-hit != 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        mkdir license-reports
        ./ci/golicense/run.sh ./antrea-bins ./license-reports
    - name: Upload licensing information
      uses: actions/upload-artifact@v2
      with:
        name: licenses.deps
        path: license-reports/ALL.deps.txt
        retention-days: 90 # max value
