name: Kind
on:
  pull_request:
    branches:
    - master
    - release-*
    - ipv6
  push:
    branches:
    - master
    - release-*
    - ipv6

env:
  KIND_VERSION: v0.9.0

jobs:
  check-changes:
    name: Check whether tests need to be run based on diff
    runs-on: [ubuntu-18.04]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        # Check out pull request's HEAD commit instead of the merge commit to
        # work-around an issue where wrong a commit is being checked out.
        # For more details, see:
        # https://github.com/actions/checkout/issues/299.
        ref: ${{ github.event.pull_request.head.sha }}
    - uses: vmware-tanzu/antrea/ci/gh-actions/has-changes@master
      id: check_diff
      with:
        args: docs/* ci/jenkins/* *.md
    outputs:
      has_changes: ${{ steps.check_diff.outputs.has_changes }}

  build-antrea-coverage-image:
    name: Build Antrea image to be used for Kind e2e tests
    needs: check-changes
    if: ${{ needs.check-changes.outputs.has_changes == 'yes' }}
    runs-on: [ubuntu-18.04]
    steps:
    - uses: actions/checkout@v2
      with:
        # Check out pull request's HEAD commit instead of the merge commit to
        # work-around an issue where wrong a commit is being checked out.
        # For more details, see:
        # https://github.com/actions/checkout/issues/299.
        ref: ${{ github.event.pull_request.head.sha }}
    - run: make build-ubuntu-coverage
    - name: Save Antrea image to tarball
      run:  docker save -o antrea-ubuntu.tar antrea/antrea-ubuntu-coverage:latest
    - name: Upload Antrea image for subsequent jobs
      uses: actions/upload-artifact@v1
      with:
        name: antrea-ubuntu
        path: antrea-ubuntu.tar

  test-e2e-encap:
    name: E2e tests on a Kind cluster on Linux
    needs: build-antrea-coverage-image
    runs-on: [ubuntu-18.04]
    steps:
    - name: Free disk space
      # https://github.com/actions/virtual-environments/issues/709
      run: |
        sudo apt-get clean
        df -h
    - uses: actions/checkout@v2
      with:
        # Check out pull request's HEAD commit instead of the merge commit to
        # work-around an issue where wrong a commit is being checked out.
        # For more details, see:
        # https://github.com/actions/checkout/issues/299.
        ref: ${{ github.event.pull_request.head.sha }}
    - uses: actions/setup-go@v1
      with:
        go-version: 1.13
    - name: Download Antrea image from previous job
      uses: actions/download-artifact@v1
      with:
        name: antrea-ubuntu
    - name: Load Antrea image
      run:  docker load -i antrea-ubuntu/antrea-ubuntu.tar
    - name: Install Kind
      run: |
        curl -Lo ./kind https://github.com/kubernetes-sigs/kind/releases/download/${KIND_VERSION}/kind-$(uname)-amd64
        chmod +x ./kind
        sudo mv kind /usr/local/bin
    - name: Run e2e tests
      run: |
        mkdir log
        mkdir test-e2e-encap-coverage
        ANTREA_LOG_DIR=$PWD/log ANTREA_COV_DIR=$PWD/test-e2e-encap-coverage ./ci/kind/test-e2e-kind.sh --encap-mode encap --coverage
    - name: Tar coverage files
      run: tar -czf test-e2e-encap-coverage.tar.gz test-e2e-encap-coverage
    - name: Upload coverage for test-e2e-encap-coverage
      uses: actions/upload-artifact@v2
      with:
        name: test-e2e-encap-coverage
        path: test-e2e-encap-coverage.tar.gz
    - name: Codecov
      uses: codecov/codecov-action@v1
      with:
        file: '*antrea*'
        flags: kind-e2e-tests
        name: codecov-test-e2e-encap
        directory: test-e2e-encap-coverage
    - name: Tar log files
      if: ${{ failure() }}
      run: tar -czf log.tar.gz log
    - name: Upload test log
      uses: actions/upload-artifact@v2
      if: ${{ failure() }}
      with:
        name: e2e-kind-encap.tar.gz
        path: log.tar.gz

  test-e2e-encap-proxy:
    name: E2e tests on a Kind cluster on Linux with proxy enabled
    needs: build-antrea-coverage-image
    runs-on: [ubuntu-18.04]
    steps:
    - name: Free disk space
      # https://github.com/actions/virtual-environments/issues/709
      run: |
        sudo apt-get clean
        df -h
    - uses: actions/checkout@v2
      with:
        # Check out pull request's HEAD commit instead of the merge commit to
        # work-around an issue where wrong a commit is being checked out.
        # For more details, see:
        # https://github.com/actions/checkout/issues/299.
        ref: ${{ github.event.pull_request.head.sha }}
    - uses: actions/setup-go@v1
      with:
        go-version: 1.13
    - name: Download Antrea image from previous job
      uses: actions/download-artifact@v1
      with:
        name: antrea-ubuntu
    - name: Load Antrea image
      run:  docker load -i antrea-ubuntu/antrea-ubuntu.tar
    - name: Install Kind
      run: |
        curl -Lo ./kind https://github.com/kubernetes-sigs/kind/releases/download/${KIND_VERSION}/kind-$(uname)-amd64
        chmod +x ./kind
        sudo mv kind /usr/local/bin
    - name: Run e2e tests
      run: |
        mkdir log
        mkdir test-e2e-encap-proxy-coverage
        ANTREA_LOG_DIR=$PWD/log ANTREA_COV_DIR=$PWD/test-e2e-encap-proxy-coverage ./ci/kind/test-e2e-kind.sh --encap-mode encap --proxy --coverage
    - name: Tar coverage files
      run: tar -czf test-e2e-encap-proxy-coverage.tar.gz test-e2e-encap-proxy-coverage
    - name: Upload coverage for test-e2e-encap-proxy-coverage
      uses: actions/upload-artifact@v2
      with:
        name: test-e2e-encap-proxy-coverage
        path: test-e2e-encap-proxy-coverage.tar.gz
    - name: Codecov
      uses: codecov/codecov-action@v1
      with:
        file: '*antrea*'
        flags: kind-e2e-tests
        name: codecov-test-e2e-encap-proxy
        directory: test-e2e-encap-proxy-coverage
    - name: Tar log files
      if: ${{ failure() }}
      run: tar -czf log.tar.gz log
    - name: Upload test log
      uses: actions/upload-artifact@v2
      if: ${{ failure() }}
      with:
        name: e2e-kind-encap-proxy.tar.gz
        path: log.tar.gz

  test-e2e-noencap:
    name: E2e tests on a Kind cluster on Linux (noEncap)
    needs: build-antrea-coverage-image
    runs-on: [ubuntu-18.04]
    steps:
    - name: Free disk space
      # https://github.com/actions/virtual-environments/issues/709
      run: |
        sudo apt-get clean
        df -h
    - uses: actions/checkout@v2
      with:
        # Check out pull request's HEAD commit instead of the merge commit to
        # work-around an issue where wrong a commit is being checked out.
        # For more details, see:
        # https://github.com/actions/checkout/issues/299.
        ref: ${{ github.event.pull_request.head.sha }}
    - uses: actions/setup-go@v1
      with:
        go-version: 1.13
    - name: Download Antrea image from previous job
      uses: actions/download-artifact@v1
      with:
        name: antrea-ubuntu
    - name: Load Antrea image
      run:  docker load -i antrea-ubuntu/antrea-ubuntu.tar
    - name: Install Kind
      run: |
        curl -Lo ./kind https://github.com/kubernetes-sigs/kind/releases/download/${KIND_VERSION}/kind-$(uname)-amd64
        chmod +x ./kind
        sudo mv kind /usr/local/bin
    - name: Run e2e tests
      run: |
        mkdir log
        mkdir test-e2e-noencap-coverage
        ANTREA_LOG_DIR=$PWD/log ANTREA_COV_DIR=$PWD/test-e2e-noencap-coverage ./ci/kind/test-e2e-kind.sh --encap-mode noEncap --coverage
    - name: Tar coverage files
      run: tar -czf test-e2e-noencap-coverage.tar.gz test-e2e-noencap-coverage
    - name: Upload coverage for test-e2e-noencap-coverage
      uses: actions/upload-artifact@v2
      with:
        name: test-e2e-noencap-coverage
        path: test-e2e-noencap-coverage.tar.gz
    - name: Codecov
      uses: codecov/codecov-action@v1
      with:
        file: '*antrea*'
        flags: kind-e2e-tests
        name: codecov-test-e2e-noencap
        directory: test-e2e-noencap-coverage
    - name: Tar log files
      if: ${{ failure() }}
      run: tar -czf log.tar.gz log
    - name: Upload test log
      uses: actions/upload-artifact@v2
      if: ${{ failure() }}
      with:
        name: e2e-kind-noencap.tar.gz
        path: log.tar.gz

  test-e2e-hybrid:
    name: E2e tests on a Kind cluster on Linux (hybrid)
    needs: build-antrea-coverage-image
    runs-on: [ubuntu-18.04]
    steps:
    - name: Free disk space
      # https://github.com/actions/virtual-environments/issues/709
      run: |
        sudo apt-get clean
        df -h
    - uses: actions/checkout@v2
      with:
        # Check out pull request's HEAD commit instead of the merge commit to
        # work-around an issue where wrong a commit is being checked out.
        # For more details, see:
        # https://github.com/actions/checkout/issues/299.
        ref: ${{ github.event.pull_request.head.sha }}
    - uses: actions/setup-go@v1
      with:
        go-version: 1.13
    - name: Download Antrea image from previous job
      uses: actions/download-artifact@v1
      with:
        name: antrea-ubuntu
    - name: Load Antrea image
      run:  docker load -i antrea-ubuntu/antrea-ubuntu.tar
    - name: Install Kind
      run: |
        curl -Lo ./kind https://github.com/kubernetes-sigs/kind/releases/download/${KIND_VERSION}/kind-$(uname)-amd64
        chmod +x ./kind
        sudo mv kind /usr/local/bin
    - name: Run e2e tests
      run: |
        mkdir log
        mkdir test-e2e-hybrid-coverage
        ANTREA_LOG_DIR=$PWD/log ANTREA_COV_DIR=$PWD/test-e2e-hybrid-coverage ./ci/kind/test-e2e-kind.sh --encap-mode hybrid --coverage
    - name: Tar coverage files
      run: tar -czf test-e2e-hybrid-coverage.tar.gz test-e2e-hybrid-coverage
    - name: Upload coverage for test-e2e-hybrid-coverage
      uses: actions/upload-artifact@v2
      with:
        name: test-e2e-hybrid-coverage
        path: test-e2e-hybrid-coverage.tar.gz
    - name: Codecov
      uses: codecov/codecov-action@v1
      with:
        file: '*antrea*'
        flags: kind-e2e-tests
        name: codecov-test-e2e-hybrid
        directory: test-e2e-hybrid-coverage
    - name: Tar log files
      if: ${{ failure() }}
      run: tar -czf log.tar.gz log
    - name: Upload test log
      uses: actions/upload-artifact@v2
      if: ${{ failure() }}
      with:
        name: e2e-kind-hybrid.tar.gz
        path: log.tar.gz

  test-e2e-encap-np:
    name: E2e tests on a Kind cluster on Linux with Antrea NetworkPolicies enabled
    needs: build-antrea-coverage-image
    runs-on: [ubuntu-18.04]
    steps:
    - name: Free disk space
      # https://github.com/actions/virtual-environments/issues/709
      run: |
        sudo apt-get clean
        df -h
    - uses: actions/checkout@v2
      with:
        # Check out pull request's HEAD commit instead of the merge commit to
        # work-around an issue where wrong a commit is being checked out.
        # For more details, see:
        # https://github.com/actions/checkout/issues/299.
        ref: ${{ github.event.pull_request.head.sha }}
    - uses: actions/setup-go@v1
      with:
        go-version: 1.13
    - name: Download Antrea image from previous job
      uses: actions/download-artifact@v1
      with:
        name: antrea-ubuntu
    - name: Load Antrea image
      run:  docker load -i antrea-ubuntu/antrea-ubuntu.tar
    - name: Install Kind
      run: |
        curl -Lo ./kind https://github.com/kubernetes-sigs/kind/releases/download/${KIND_VERSION}/kind-$(uname)-amd64
        chmod +x ./kind
        sudo mv kind /usr/local/bin
    - name: Run e2e tests
      run: |
        mkdir log
        mkdir test-e2e-encap-np-coverage 
        ANTREA_LOG_DIR=$PWD/log ANTREA_COV_DIR=$PWD/test-e2e-encap-np-coverage ./ci/kind/test-e2e-kind.sh --encap-mode encap --np --coverage
    - name: Tar coverage files
      run: tar -czf test-e2e-encap-np-coverage.tar.gz test-e2e-encap-np-coverage
    - name: Upload coverage for test-e2e-encap-np-coverage
      uses: actions/upload-artifact@v2
      with:
        name: test-e2e-encap-np-coverage
        path: test-e2e-encap-np-coverage.tar.gz
    - name: Codecov
      uses: codecov/codecov-action@v1
      with:
        file: '*antrea*'
        flags: kind-e2e-tests
        name: codecov-test-e2e-np-encap
        directory: test-e2e-encap-np-coverage
    - name: Tar log files
      if: ${{ failure() }}
      run: tar -czf log.tar.gz log
    - name: Upload test log
      uses: actions/upload-artifact@v2
      if: ${{ failure() }}
      with:
        name: e2e-kind-hybrid.tar.gz
        path: log.tar.gz

  build-antrea-image:
    name: Build Antrea image to be used for Kind netpol tests
    needs: check-changes
    if: ${{ needs.check-changes.outputs.has_changes == 'yes' }}
    runs-on: [ubuntu-18.04]
    steps:
    - uses: actions/checkout@v2
      with:
        # Check out pull request's HEAD commit instead of the merge commit to
        # work-around an issue where wrong a commit is being checked out.
        # For more details, see:
        # https://github.com/actions/checkout/issues/299.
        ref: ${{ github.event.pull_request.head.sha }}
    - run: make
    - name: Save Antrea image to tarball
      run:  docker save -o antrea-ubuntu-netpol.tar antrea/antrea-ubuntu:latest
    - name: Upload Antrea image for subsequent jobs
      uses: actions/upload-artifact@v1
      with:
        name: antrea-ubuntu-netpol
        path: antrea-ubuntu-netpol.tar

  test-netpol-tmp:
    name: Run experimental network policy tests (netpol) on Kind cluster
    needs: build-antrea-image
    runs-on: [ubuntu-18.04]
    steps:
    - name: Free disk space
      # https://github.com/actions/virtual-environments/issues/709
      run: |
        sudo apt-get clean
        df -h
    - uses: actions/checkout@v2
      with:
        # Check out pull request's HEAD commit instead of the merge commit to
        # work-around an issue where wrong a commit is being checked out.
        # For more details, see:
        # https://github.com/actions/checkout/issues/299.
        ref: ${{ github.event.pull_request.head.sha }}
    - uses: actions/setup-go@v1
      with:
        go-version: 1.13
    - name: Download Antrea image from previous job
      uses: actions/download-artifact@v1
      with:
        name: antrea-ubuntu-netpol
    - name: Load Antrea image
      run:  docker load -i antrea-ubuntu-netpol/antrea-ubuntu-netpol.tar
    - name: Install Kind
      run: |
        curl -Lo ./kind https://github.com/kubernetes-sigs/kind/releases/download/${KIND_VERSION}/kind-$(uname)-amd64
        chmod +x ./kind
        sudo mv kind /usr/local/bin
    - name: Build netpol Docker image
      working-directory: hack/netpol
      run: make
    - name: Run netpol tests
      working-directory: hack/netpol
      run: ./test-kind.sh

  validate-prometheus-metrics-doc:
    name: Validate metrics in Prometheus document match running deployment's
    needs: build-antrea-image
    runs-on: [ubuntu-18.04]
    steps:
      - name: Free disk space
        # https://github.com/actions/virtual-environments/issues/709
        run: |
          sudo apt-get clean
          df -h
      - uses: actions/checkout@v2
        with:
          # Check out pull request's HEAD commit instead of the merge commit to
          # work-around an issue where wrong a commit is being checked out.
          # For more details, see:
          # https://github.com/actions/checkout/issues/299.
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Download Antrea image from previous job
        uses: actions/download-artifact@v1
        with:
          name: antrea-ubuntu-netpol
      - name: Load Antrea image
        run:  docker load -i antrea-ubuntu-netpol/antrea-ubuntu-netpol.tar
      - name: Install Kind
        run: |
          curl -Lo ./kind https://github.com/kubernetes-sigs/kind/releases/download/${KIND_VERSION}/kind-$(uname)-amd64
          chmod +x ./kind
          sudo mv kind /usr/local/bin
      - name: Validate document
        run: |
          ./ci/kind/validate-metrics-doc.sh
