name: Process new release

on:
  release:
    types: [published]

jobs:
  upload-release-assets:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go using version from go.mod
      uses: actions/setup-go@v3
      with:
        go-version-file: 'go.mod'
    - name: Build assets
      env:
        TAG: ${{ github.ref }}
        PRERELEASE: ${{ github.event.release.prerelease }}
      run: |
        mkdir assets
        VERSION="${TAG:10}" ./hack/release/prepare-assets.sh ./assets
    - name: Upload antctl-darwin-x86_64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./assets/antctl-darwin-x86_64
        asset_name: antctl-darwin-x86_64
        asset_content_type: application/octet-stream
    - name: Upload antctl-linux-arm
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./assets/antctl-linux-arm
        asset_name: antctl-linux-arm
        asset_content_type: application/octet-stream
    - name: Upload antctl-linux-arm64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./assets/antctl-linux-arm64
        asset_name: antctl-linux-arm64
        asset_content_type: application/octet-stream
    - name: Upload antctl-linux-x86_64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./assets/antctl-linux-x86_64
        asset_name: antctl-linux-x86_64
        asset_content_type: application/octet-stream
    - name: Upload antctl-windows-x86_64.exe
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./assets/antctl-windows-x86_64.exe
        asset_name: antctl-windows-x86_64.exe
        asset_content_type: application/octet-stream
    - name: Upload antrea-octant-plugin-darwin-x86_64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./assets/antrea-octant-plugin-darwin-x86_64
        asset_name: antrea-octant-plugin-darwin-x86_64
        asset_content_type: application/octet-stream
    - name: Upload antrea-octant-plugin-linux-arm
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./assets/antrea-octant-plugin-linux-arm
        asset_name: antrea-octant-plugin-linux-arm
        asset_content_type: application/octet-stream
    - name: Upload antrea-octant-plugin-linux-arm64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./assets/antrea-octant-plugin-linux-arm64
        asset_name: antrea-octant-plugin-linux-arm64
        asset_content_type: application/octet-stream
    - name: Upload antrea-octant-plugin-linux-x86_64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./assets/antrea-octant-plugin-linux-x86_64
        asset_name: antrea-octant-plugin-linux-x86_64
        asset_content_type: application/octet-stream
    - name: Upload antrea-octant-plugin-windows-x86_64.exe
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./assets/antrea-octant-plugin-windows-x86_64.exe
        asset_name: antrea-octant-plugin-windows-x86_64.exe
        asset_content_type: application/octet-stream
    - name: Upload antrea.yml
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./assets/antrea.yml
        asset_name: antrea.yml
        asset_content_type: application/octet-stream
    - name: Upload antrea-crds.yml
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./assets/antrea-crds.yml
        asset_name: antrea-crds.yml
        asset_content_type: application/octet-stream
    - name: Upload antrea-ipsec.yml
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./assets/antrea-ipsec.yml
        asset_name: antrea-ipsec.yml
        asset_content_type: application/octet-stream
    - name: Upload antrea-eks.yml
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./assets/antrea-eks.yml
        asset_name: antrea-eks.yml
        asset_content_type: application/octet-stream
    - name: Upload antrea-gke.yml
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./assets/antrea-gke.yml
        asset_name: antrea-gke.yml
        asset_content_type: application/octet-stream
    - name: Upload antrea-aks.yml
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./assets/antrea-aks.yml
        asset_name: antrea-aks.yml
        asset_content_type: application/octet-stream
    - name: Upload antrea-octant.yml
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./assets/antrea-octant.yml
        asset_name: antrea-octant.yml
        asset_content_type: application/octet-stream
    - name: Upload antrea-windows.yml
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./assets/antrea-windows.yml
        asset_name: antrea-windows.yml
        asset_content_type: application/octet-stream
    - name: Upload flow-aggregator.yml
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./assets/flow-aggregator.yml
        asset_name: flow-aggregator.yml
        asset_content_type: application/octet-stream
    - name: Upload antrea-multicluster-leader-global.yml
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./assets/antrea-multicluster-leader-global.yml
        asset_name: antrea-multicluster-leader-global.yml
        asset_content_type: application/octet-stream
    - name: Upload antrea-multicluster-leader-namespaced.yml
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./assets/antrea-multicluster-leader-namespaced.yml
        asset_name: antrea-multicluster-leader-namespaced.yml
        asset_content_type: application/octet-stream
    - name: Upload antrea-multicluster-member.yml
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./assets/antrea-multicluster-member.yml
        asset_name: antrea-multicluster-member.yml
        asset_content_type: application/octet-stream
    - name: Upload antrea-agent-linux-x86_64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./assets/antrea-agent-linux-x86_64
        asset_name: antrea-agent-linux-x86_64
        asset_content_type: application/octet-stream
    - name: Upload antrea-agent-linux-arm64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./assets/antrea-agent-linux-arm64
        asset_name: antrea-agent-linux-arm64
        asset_content_type: application/octet-stream
    - name: Upload antrea-agent-linux-arm
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./assets/antrea-agent-linux-arm
        asset_name: antrea-agent-linux-arm
        asset_content_type: application/octet-stream
    - name: Upload antrea-agent-windows-x86_64.exe
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./assets/antrea-agent-windows-x86_64.exe
        asset_name: antrea-agent-windows-x86_64.exe
        asset_content_type: application/octet-stream
    - name: Upload antrea-cni-windows-x86_64.exe
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./assets/antrea-cni-windows-x86_64.exe
        asset_name: antrea-cni-windows-x86_64.exe
        asset_content_type: application/octet-stream
    - name: Upload Start-AntreaAgent.ps1
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./assets/Start-AntreaAgent.ps1
        asset_name: Start-AntreaAgent.ps1
        asset_content_type: application/octet-stream
    - name: Upload Antrea Helm chart archive
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./assets/antrea-chart.tgz
        asset_name: antrea-chart.tgz
        asset_content_type: application/octet-stream
    - name: Upload Flow Aggregator Helm chart archive
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./assets/flow-aggregator-chart.tgz
        asset_name: flow-aggregator-chart.tgz
        asset_content_type: application/octet-stream
    - name: Upload install-vm.sh
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./assets/install-vm.sh
        asset_name: install-vm.sh
        asset_content_type: application/octet-stream
    - name: Upload install-vm.ps1
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./assets/install-vm.ps1
        asset_name: install-vm.ps1
        asset_content_type: application/octet-stream

  update-website:
    name: Trigger website update for release
    needs: upload-release-assets
    runs-on: ubuntu-latest
    steps:
    - id: get-version
      env:
        TAG: ${{ github.ref }}
      run: |
        version=${TAG:10}
        echo "::set-output name=version::$version"
    - name: Update website source
      uses: benc-uk/workflow-dispatch@v121
      with:
        repo: antrea-io/website
        ref: refs/heads/main
        workflow: Update website source
        token: ${{ secrets.ANTREA_WEBSITE_WORKFLOW_DISPATCH_PAT }}
        inputs: ${{ format('{{ "antrea-repository":"antrea-io/antrea", "antrea-ref":"{0}" }}', steps.get-version.outputs.version) }}
    - name: Update Helm index with Antrea archive
      uses: benc-uk/workflow-dispatch@v121
      with:
        repo: antrea-io/website
        ref: refs/heads/main
        workflow: Update Helm index
        token: ${{ secrets.ANTREA_WEBSITE_WORKFLOW_DISPATCH_PAT }}
        inputs: ${{ format('{{ "archive-url":"https://github.com/antrea-io/antrea/releases/download/{0}/antrea-chart.tgz" }}', steps.get-version.outputs.version) }}
    - name: Update Helm index with Flow Aggregator archive
      uses: benc-uk/workflow-dispatch@v121
      with:
        repo: antrea-io/website
        ref: refs/heads/main
        workflow: Update Helm index
        token: ${{ secrets.ANTREA_WEBSITE_WORKFLOW_DISPATCH_PAT }}
        inputs: ${{ format('{{ "archive-url":"https://github.com/antrea-io/antrea/releases/download/{0}/flow-aggregator-chart.tgz" }}', steps.get-version.outputs.version) }}
