name: Update the antrea/openvswitch image every 12 hours

on:
  schedule:
    # every 12 hours
    - cron: '0 */12 * * *'

jobs:
  build:
    if: github.repository == 'vmware-tanzu/antrea'
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Build antrea/openvswitch Docker image and push to registry
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        OVS_VERSION: 2.14.2
      run: |
        cd build/images/ovs/
        docker pull antrea/openvswitch-debs:$OVS_VERSION || true
        docker pull antrea/openvswitch:$OVS_VERSION || true
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        ./build.sh --pull --push
        cd ../base/
        ./build.sh --pull --push
  skip:
    if: github.repository != 'vmware-tanzu/antrea'
    runs-on: [ubuntu-latest]
    steps:
      - name: Skip
        run: |
          echo "Skipping OVS image update because workflow cannot be run from fork"
