name: Verify docs

on:
  schedule:
    # every day at 9am
    - cron: '0 9 * * *'

jobs:
  verify:
    name: Verify docs and spelling
    if: github.repository == 'antrea-io/antrea'
    runs-on: [ubuntu-latest]
    steps:
    - name: Check-out code
      uses: actions/checkout@v6
    - name: Set up Go using version from .go-version
      uses: actions/setup-go@v6
      with:
        go-version-file: '.go-version'
    - name: Run verify scripts
      run: make verify
    - name: Checking for broken Markdown links for main branch
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        folder-path: './docs'
        file-path: './README.md, ./CHANGELOG.md, ./CONTRIBUTING.md, ./GOVERNANCE.md, ./MAINTAINERS.md, ./ROADMAP.md, ./SECURITY.md'
        config-file: 'hack/.md_links_config.json'
    - name: Markdownlint
      run: |
        sudo npm install -g markdownlint-cli@0.38.0
        make markdownlint 
